version: "3.8"

services:
    mariadb:
        container_name: mariadb
        image: mariadb
        networks:
            - inception
        build:
            context: requirements/mariadb
            dockerfile: Dockerfile
            args:
                DATABASE: $DATABASE
                ADMIN_USER: $ADMIN_USER
                ADMIN_PASSWORD: $ADMIN_PASSWORD
                ROOT_PASSWORD: $ROOT_PASSWORD
        env_file: .env
        volumes:
            - mariadb:/var/lib/mysql
        restart: unless-stopped

    nginx:
        container_name: nginx
        image: nginx
        networks:
            - inception
        depends_on:
            - wordpress
        build:
            context: requirements/nginx
            dockerfile: Dockerfile
            args:
                DOMAIN_NAME: $DOMAIN_NAME
        env_file: .env
        volumes:
            - wordpress:/var/www/html
        restart: on-failure
        ports:
            - "443:443"

    wordpress:
        container_name: wordpress
        image: wordpress
        networks:
            - inception
        depends_on:
            - mariadb
        build:
            context: requirements/wordpress
            dockerfile: Dockerfile
        env_file: .env
        volumes:
            - wordpress:/var/www/html
        restart: on-failure

volumes:
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: $WORDPRESS_VOLUME
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            type: 'none'
            o : 'bind'
            device: $MARIADB_VOLUME

networks:
    inception:
        name: inception
        driver: bridge
