version		:	"3.8"

services	:
			mariadb:
					container_name: mariadb
					networks: inception
					build:
							context: requirements/mariadb
							dockerfile: Dockerfile
							env_file: .env
					volumes: mariadb: /var/lib/mysql
					restart: unless-stopped
					expose: "3306"

			nginx:
					container_name: nginx
					networks: inception
					build:
							context: requirements/mariadb
							dockerfile: Dockerfile
							env_file: .env
					volumes: wordpress: /var/www/wordpress
					restart: unless-stopped
					expose: "3306"

			wordpress:
					container_name: nginx
					networks: inception
					build:
							context: requirements/wordpress
							dockerfile: Dockerfile
							env_file: .env
					volumes: wordpress: /var/www/wordpress
					restart: unless-stopped
					expose: "3306"