version: "3.8"

services:
    mariadb:
        container_name: mariadb
        networks:
            - inception
        build:
            context: requirements/mariadb
            dockerfile: Dockerfile
            env_file: .env
        volumes:
            - mariadb:/var/lib/mysql
        restart: unless-stopped
        expose:
            - "3306"

    nginx:
        container_name: nginx
        networks:
            - inception
        build:
            context: requirements/nginx
            dockerfile: Dockerfile
            env_file: .env
        volumes:
            - wordpress:/var/www/wordpress
        restart: unless-stopped
        expose:
            - "80"

    wordpress:
        container_name: wordpress
        networks:
            - inception
        build:
            context: requirements/wordpress
            dockerfile: Dockerfile
            env_file: .env
        volumes:
            - wordpress:/var/www/wordpress
        restart: unless-stopped
        expose:
            - "80"

volumes:
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            device: /home/twang/data/wordpress

    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            device: /home/twang/data/mariadb

networks:
    inception:
        driver: bridge
