version: "3.8"

services:
    mariadb:
        container_name: mariadb
        image: mariadb
        networks:
            - inception
        build:
            context: requirements/mariadb
            dockerfile: Dockerfile
            args:
                MYSQL_DATABASE: $MYSQL_DATABASE
                MYSQL_USER: $MYSQL_USER
                MYSQL_PASSWORD: $MYSQL_PASSWORD
                MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        env_file: .env
        volumes:
            - mariadb:/var/lib/mysql
        restart: unless-stopped
        expose:
            - "3306"

    nginx:
        container_name: nginx
        image: nginx
        networks:
            - inception
        depends_on:
            - wordpress
        build:
            context: requirements/nginx
            dockerfile: Dockerfile
        env_file: .env
        volumes:
            - wordpress:/var/www/wordpress
        restart: on-failure
        ports:
            - "443:443"

    wordpress:
        container_name: wordpress
        image: wordpress
        networks:
            - inception
        depends_on:
            - mariadb
        build:
            context: requirements/wordpress
            dockerfile: Dockerfile
        env_file: .env
        volumes:
            - wordpress:/var/www/wordpress
        restart: on-failure
        expose:
            - "9000"

volumes:
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: /home/twang/data/wordpress

    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            type: 'none'
            o : 'bind'
            device: /home/twang/data/mariadb

networks:
    inception:
        driver: bridge
